//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiscoRegistryEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class RegistrySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RegistrySettings defaultInstance = ((RegistrySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RegistrySettings())));
        
        public static RegistrySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HKEY_LOCAL_MACHINE\\")]
        public string RLocBaseKey {
            get {
                return ((string)(this["RLocBaseKey"]));
            }
            set {
                this["RLocBaseKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SYSTEM\\CurrentControl­Set\\Services\\CVirta")]
        public string RLocSubKey {
            get {
                return ((string)(this["RLocSubKey"]));
            }
            set {
                this["RLocSubKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\River Logic\\NajirTest")]
        public string RLocSubKeyTry {
            get {
                return ((string)(this["RLocSubKeyTry"]));
            }
            set {
                this["RLocSubKeyTry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cisco Systems VPN Adapter for 64-bit")]
        public string CorrectValue {
            get {
                return ((string)(this["CorrectValue"]));
            }
            set {
                this["CorrectValue"] = value;
            }
        }
    }
}
